ubuntu_task:
  matrix:
    - name: Ubuntu LTS ARM64 GCC
      arm_container:
        image: arm64v8/ubuntu:jammy
      env:
        COMPILER: gcc
        UPLOAD: 1
    - name: Ubuntu LTS ARM32 GCC
      arm_container:
        image: arm32v7/ubuntu:jammy
      env:
        COMPILER: gcc
        UPLOAD: 1
    - name: Ubuntu LTS ARM64 Clang
      arm_container:
        image: arm64v8/ubuntu:jammy
      env:
        COMPILER: clang
        UPLOAD: 0
    - name: Ubuntu LTS ARM32 Clang
      arm_container:
        image: arm32v7/ubuntu:jammy
      env:
        COMPILER: clang
        UPLOAD: 0
    - name: Ubuntu Rolling ARM64 GCC
      arm_container:
        image: arm64v8/ubuntu:rolling
      env:
        COMPILER: gcc
        UPLOAD: 0
    - name: Ubuntu Rolling ARM32 GCC
      arm_container:
        image: arm32v7/ubuntu:rolling
      env:
        COMPILER: gcc
        UPLOAD: 0
    - name: Ubuntu Rolling ARM64 Clang
      arm_container:
        image: arm64v8/ubuntu:rolling
      env:
        COMPILER: clang
        UPLOAD: 0
    - name: Ubuntu Rolling ARM32 Clang
      arm_container:
        image: arm32v7/ubuntu:rolling
      env:
        COMPILER: clang
        UPLOAD: 0
  env:
    GITHUB_TOKEN: ENCRYPTED[80867839ea1cae036c24d6491696b07aeee67dee7e558714d0031f84e338ec415d266fb19e482d7430826121cfe39d2c]
    APPIMAGEVER: 13
    QTIFWVER: 4.5.1
    NJOBS: 4
  env:
    only_if: ${CIRRUS_TAG} == ""
    DAILY_BUILD: 1
  env:
    only_if: ${CIRRUS_TAG} != ""
    DAILY_BUILD: 0
  arm_container:
    cpu: 2
    memory: 4G
  timeout_in: 60m
  install_script:
    - chmod +x ports/ci/linux-ubuntu/install_deps.sh
    - ./ports/ci/linux-ubuntu/install_deps.sh
  script:
    - chmod +x ports/ci/linux-ubuntu/build.sh
    - ./ports/ci/linux-ubuntu/build.sh
  deploy_script:
    - chmod +x ports/ci/linux-ubuntu/deploy.sh
    - ./ports/ci/linux-ubuntu/deploy.sh
  upload_script:
    - chmod +x ports/ci/linux-ubuntu/upload.sh
    - ./ports/ci/linux-ubuntu/upload.sh

mac_task:
  matrix:
    - name: MacOS Ventura (13.0)
      macos_instance:
        image: ghcr.io/cirruslabs/macos-ventura-base:latest
      env:
        UPLOAD: 0
    - name: MacOS Monterrey (12.0)
      macos_instance:
        image: ghcr.io/cirruslabs/macos-monterey-base:latest
      env:
        UPLOAD: 1
  env:
    GITHUB_TOKEN: ENCRYPTED[80867839ea1cae036c24d6491696b07aeee67dee7e558714d0031f84e338ec415d266fb19e482d7430826121cfe39d2c]
    HOMEBREW_PATH: /opt/homebrew
    NJOBS: 4
  env:
    only_if: ${CIRRUS_TAG} == ""
    DAILY_BUILD: 1
  env:
    only_if: ${CIRRUS_TAG} != ""
    DAILY_BUILD: 0
  macos_instance:
    cpu: 2
    memory: 4G
  timeout_in: 60m
  install_script:
    - chmod +x ports/ci/mac/install_deps.sh
    - ./ports/ci/mac/install_deps.sh
  script:
    - chmod +x ports/ci/mac/build.sh
    - ./ports/ci/mac/build.sh
  deploy_script:
    - chmod +x ports/ci/mac/deploy.sh
    - ./ports/ci/mac/deploy.sh
  upload_script:
    - chmod +x ports/ci/mac/upload.sh
    - ./ports/ci/mac/upload.sh

freebsd_task:
  env:
    COMPILER: clang
    NJOBS: 4
  freebsd_instance:
    matrix:
      image_family: freebsd-13-0-snap
      image_family: freebsd-12-2
    cpu: 2
    memory: 4G
  timeout_in: 60m
  install_script:
    - chmod +x ports/ci/freebsd/install_deps.sh
    - ./ports/ci/freebsd/install_deps.sh
  script:
    - chmod +x ports/ci/freebsd/build.sh
    - ./ports/ci/freebsd/build.sh
  deploy_script:
    - chmod +x ports/ci/freebsd/deploy.sh
    - ./ports/ci/freebsd/deploy.sh
