version: 8.7.1.{build}-{branch}
os: MinGW

image: Visual Studio 2019

platform:
  - x64

build:
  parallel: true
  verbosity: detailed

configuration:
  - release
#  - debug

branches:
  only:
  - master

environment:
  global:
    INSTALL_PREFIX: C:/projects/webcamoid/ports/deploy/temp_priv/usr
    # api key from https://bintray.com/profile/edit
    # encrypted in https://ci.appveyor.com/tools/encrypt
    BT_KEY:
      secure: seneRk4ppI4bquIsdweI8pd8FT0RXUvU2LOUNGSBEA28IhFQijypil2CfC3WtJxa

  matrix:
    - PLATFORM: x86
    - PLATFORM: x64

install:
  - echo export PLATFORM=%PLATFORM% >> C:\projects\webcamoid\ports\ci\appveyor\environment.sh
  - type C:\projects\webcamoid\ports\ci\appveyor\environment.sh
  - C:\msys64\usr\bin\bash -lc "cd /c/projects/webcamoid && ./ports/ci/appveyor/install_deps.sh"

build_script:
  - echo export PLATFORM=%PLATFORM% >> C:\projects\webcamoid\ports\ci\appveyor\environment.sh
  - echo export INSTALL_PREFIX=%INSTALL_PREFIX% >> C:\projects\webcamoid\ports\ci\appveyor\environment.sh
  - C:\msys64\usr\bin\bash -lc "cd /c/projects/webcamoid && ./ports/ci/appveyor/build.sh

after_build:
  - echo export PLATFORM=%PLATFORM% >> C:\projects\webcamoid\ports\ci\appveyor\environment.sh
  - C:\msys64\usr\bin\bash -lc "cd /c/projects/webcamoid && ./ports/ci/appveyor/deploy.sh"
  - ports\ci\appveyor\push_artifacts.bat

deploy_script:
  - ports\ci\appveyor\upload.bat

notifications:
  - provider: Email
    to:
      - hipersayan.x@gmail.com
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true
