name: Android Full

on: [push, pull_request]

env:
  QTVER_ANDROID: 6.6.3
  ANDROID_MINIMUM_PLATFORM: 24
  ANDROID_TARGET_PLATFORM: 34
  DOCKERIMG: archlinux:latest
  ARCH_ROOT_URL: https://mirror.rackspace.com/archlinux
  NJOBS: 4

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 10
      fail-fast: false
      matrix:
       include:
         - target_arch: armeabi-v7a
           upload: 0
         - target_arch: arm64-v8a
           upload: 0
         - target_arch: x86
           upload: 0
         - target_arch: x86_64
           upload: 0
         - target_arch: armeabi-v7a:arm64-v8a:x86:x86_64
           upload: 1
    env:
      TARGET_ARCH: ${{ matrix.target_arch }}
      UPLOAD: ${{ matrix.upload }}
    steps:
    - uses: actions/checkout@v2
    - name: Release build
      uses: addnab/docker-run-action@v3
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: gcr.io
        image: ${{ env.DOCKERIMG }}
        options: >-
          -v ${{ github.workspace }}:/sources
          -e GITHUB_REF=${{ env.GITHUB_REF }}
          -e GITHUB_SERVER_URL=${{ env.GITHUB_SERVER_URL }}
          -e GITHUB_REPOSITORY=${{ env.GITHUB_REPOSITORY }}
          -e GITHUB_RUN_ID=${{ env.GITHUB_RUN_ID }}
          -e GIT_COMMIT_SHA=${{ env.GITHUB_SHA }}
          -e GIT_BRANCH_NAME=${{ env.GITHUB_REF_NAME }}
          -e FILE_PASSWORD=${{ secrets.FILE_PASSWORD }}
          -e DOCKERIMG=${{ env.DOCKERIMG }}
          -e ARCH_ROOT_URL=${{ env.ARCH_ROOT_URL }}
          -e QTVER_ANDROID=${{ env.QTVER_ANDROID }}
          -e ANDROID_MINIMUM_PLATFORM=${{ env.ANDROID_MINIMUM_PLATFORM }}
          -e ANDROID_TARGET_PLATFORM=${{ env.ANDROID_TARGET_PLATFORM }}
          -e TARGET_ARCH=${{ env.TARGET_ARCH }}
          -e NJOBS=${{ env.NJOBS }}
          -e UPLOAD=${{ matrix.upload }}
        run: |
          cd /sources
          echo
          echo Install dependencies
          echo
          chmod +x ports/ci/android-full/install_deps.sh
          ./ports/ci/android-full/install_deps.sh
          echo
          echo Release Build
          echo
          chmod +x ports/ci/android-full/build.sh
          ./ports/ci/android-full/build.sh
          echo
          echo Release Deploy
          echo
          chmod +x ports/ci/android-full/deploy.sh
          ./ports/ci/android-full/deploy.sh
    - name: Daily build
      uses: addnab/docker-run-action@v3
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: gcr.io
        image: ${{ env.DOCKERIMG }}
        options: >-
          -v ${{ github.workspace }}:/sources
          -e GITHUB_REF=${{ env.GITHUB_REF }}
          -e GITHUB_SERVER_URL=${{ env.GITHUB_SERVER_URL }}
          -e GITHUB_REPOSITORY=${{ env.GITHUB_REPOSITORY }}
          -e GITHUB_RUN_ID=${{ env.GITHUB_RUN_ID }}
          -e GIT_COMMIT_SHA=${{ env.GITHUB_SHA }}
          -e GIT_BRANCH_NAME=${{ env.GITHUB_REF_NAME }}
          -e FILE_PASSWORD=${{ secrets.FILE_PASSWORD }}
          -e DOCKERIMG=${{ env.DOCKERIMG }}
          -e ARCH_ROOT_URL=${{ env.ARCH_ROOT_URL }}
          -e QTVER_ANDROID=${{ env.QTVER_ANDROID }}
          -e ANDROID_MINIMUM_PLATFORM=${{ env.ANDROID_MINIMUM_PLATFORM }}
          -e ANDROID_TARGET_PLATFORM=${{ env.ANDROID_TARGET_PLATFORM }}
          -e TARGET_ARCH=${{ env.TARGET_ARCH }}
          -e NJOBS=${{ env.NJOBS }}
          -e UPLOAD=${{ matrix.upload }}
          -e DAILY_BUILD=1
        run: |
          cd /sources
          echo
          echo Install dependencies
          echo
          chmod +x ports/ci/android-full/install_deps.sh
          ./ports/ci/android-full/install_deps.sh
          echo
          echo Daily Build
          echo
          chmod +x ports/ci/android-full/build.sh
          ./ports/ci/android-full/build.sh
          echo
          echo Daily Deploy
          echo
          chmod +x ports/ci/android-full/deploy.sh
          ./ports/ci/android-full/deploy.sh
