name: Android Basic

on: [push, pull_request]

env:
  QTVER_ANDROID: 6.6.1
  SDKVER: 10406996
  NDKVER: r26b
  ANDROID_BUILD_TOOLS_VERSION: 34.0.0
  NJOBS: 4

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 10
      fail-fast: false
      matrix:
       include:
         - android_platform: 24
           target_arch: armeabi-v7a
         - android_platform: 24
           target_arch: arm64-v8a
         - android_platform: 24
           target_arch: x86
         - android_platform: 24
           target_arch: x86_64
         - android_platform: 24
           target_arch: armeabi-v7a:arm64-v8a:x86:x86_64
           upload: 1
    env:
      ANDROID_PLATFORM: ${{ matrix.android_platform }}
      TARGET_ARCH: ${{ matrix.target_arch }}
      UPLOAD: ${{ matrix.upload }}
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        chmod +x ports/ci/android-basic/install_deps.sh
        ./ports/ci/android-basic/install_deps.sh
    - name: Release Build
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      run: |
        chmod +x ports/ci/android-basic/build.sh
        ./ports/ci/android-basic/build.sh
    - name: Release Deploy
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      run: |
        chmod +x ports/ci/android-basic/deploy.sh
        ./ports/ci/android-basic/deploy.sh
    - name: Daily Build
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      env:
        DAILY_BUILD: 1
      run: |
        chmod +x ports/ci/android-basic/build.sh
        ./ports/ci/android-basic/build.sh
    - name: Daily Deploy
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      env:
        DAILY_BUILD: 1
      run: |
        chmod +x ports/ci/android-basic/deploy.sh
        ./ports/ci/android-basic/deploy.sh
    - name: Release Upload
      uses: softprops/action-gh-release@v1
      if: ${{ startsWith(github.ref, 'refs/tags/') && matrix.upload }}
      with:
        repository: webcamoid/WebcamoidPrivate
        files: webcamoid-packages/android-basic/*
      env:
        GITHUB_TOKEN: ${{ secrets.UPLOAD_TOKEN }}
    - name: Daily Build Upload
      uses: softprops/action-gh-release@v1
      if: ${{ !startsWith(github.ref, 'refs/tags/') && matrix.upload && github.ref == 'refs/heads/master' }}
      with:
        repository: webcamoid/WebcamoidPrivate
        body: "${{ github.event.head_commit.message }} (commit: [${{ github.sha }}](https://github.com/webcamoid/webcamoid/commit/${{ github.sha }}))<hr>**Note**: Ignore the commit information of the tag, the files in the release keep updating with every new build, these packages were built from [${{ github.sha }}](https://github.com/webcamoid/webcamoid/commit/${{ github.sha }}) commit."
        prerelease: true
        files: webcamoid-packages/android-basic/*
        name: Daily Build
        tag_name: daily-build
      env:
        GITHUB_TOKEN: ${{ secrets.UPLOAD_TOKEN }}
