name: Flatpak

on: [push, pull_request]

env:
  RUNTIME_VERSION: 5.15-21.08

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        chmod +x ports/ci/flatpak/install_deps.sh
        ./ports/ci/flatpak/install_deps.sh
    - name: Release Build
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      run: |
        chmod +x ports/ci/flatpak/build.sh
        ./ports/ci/flatpak/build.sh
    - name: Release Deploy
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      run: |
        chmod +x ports/ci/flatpak/deploy.sh
        ./ports/ci/flatpak/deploy.sh
    - name: Daily Build
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      env:
        DAILY_BUILD: 1
      run: |
        chmod +x ports/ci/flatpak/build.sh
        ./ports/ci/flatpak/build.sh
    - name: Daily Deploy
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      env:
        DAILY_BUILD: 1
      run: |
        chmod +x ports/ci/flatpak/deploy.sh
        ./ports/ci/flatpak/deploy.sh
