name: Flatpak

on: [push, pull_request]

env:
  RUNTIME_VERSION: 6.6

jobs:
  build:
    name: Flatpak x86_64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        chmod +x ports/ci/flatpak/install_deps.sh
        ./ports/ci/flatpak/install_deps.sh
    - name: Release Build
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      run: |
        chmod +x ports/ci/flatpak/build.sh
        ./ports/ci/flatpak/build.sh
    - name: Release Deploy
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      run: |
        chmod +x ports/ci/flatpak/deploy.sh
        ./ports/ci/flatpak/deploy.sh
    - name: Daily Build
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      env:
        DAILY_BUILD: 1
      run: |
        chmod +x ports/ci/flatpak/build.sh
        ./ports/ci/flatpak/build.sh
    - name: Daily Deploy
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      env:
        DAILY_BUILD: 1
      run: |
        chmod +x ports/ci/flatpak/deploy.sh
        ./ports/ci/flatpak/deploy.sh
    - name: Release Upload
      uses: softprops/action-gh-release@v1
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      with:
        repository: webcamoid/WebcamoidPrivate
        files: webcamoid-packages/linux/*
      env:
        GITHUB_TOKEN: ${{ secrets.UPLOAD_TOKEN }}
    - name: Daily Build Upload
      uses: softprops/action-gh-release@v1
      if: ${{ !startsWith(github.ref, 'refs/tags/') && github.ref == 'refs/heads/master' }}
      with:
        repository: webcamoid/WebcamoidPrivate
        body: "${{ github.event.head_commit.message }} (commit: [${{ github.sha }}](https://github.com/webcamoid/webcamoid/commit/${{ github.sha }}))<hr>**Note**: Ignore the commit information of the tag, the files in the release keep updating with every new build, these packages were built from [${{ github.sha }}](https://github.com/webcamoid/webcamoid/commit/${{ github.sha }}) commit."
        prerelease: true
        files: webcamoid-packages/linux/*
        name: Daily Build
        tag_name: daily-build
      env:
        GITHUB_TOKEN: ${{ secrets.UPLOAD_TOKEN }}
  multiarch:
    name: Flatpak Multiarch
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 10
      fail-fast: false
      matrix:
       include:
         - distro: ubuntu_latest
           architecture: armv7
           compiler: gcc
           upload: 1
         - distro: ubuntu_latest
           architecture: aarch64
           compiler: gcc
           upload: 1
    steps:
    - uses: actions/checkout@v2
    - name: Release build
      uses: uraimo/run-on-arch-action@v2
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      with:
        arch: ${{ matrix.architecture }}
        distro: ${{ matrix.distro }}
        githubToken: ${{ github.token }}
        dockerRunArgs: |
          -v "${{ github.workspace }}:/sources"
        env: |
          GITHUB_REF: "${{ env.GITHUB_REF }}"
          GITHUB_SERVER_URL: "${{ env.GITHUB_SERVER_URL }}"
          GITHUB_REPOSITORY: "${{ env.GITHUB_REPOSITORY }}"
          GITHUB_RUN_ID: "${{ env.GITHUB_RUN_ID }}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILE_PASSWORD: ${{ secrets.FILE_PASSWORD }}
          DISTRO: ${{ matrix.distro }}
          ARCHITECTURE: ${{ matrix.architecture }}
          NJOBS: ${{ env.NJOBS }}
          UPLOAD: ${{ matrix.upload }}
        run: |
          cd /sources
          echo
          echo Install dependencies
          echo
          chmod +x ports/ci/flatpak/install_deps.sh
          ./ports/ci/flatpak/install_deps.sh
          echo
          echo Release Build
          echo
          chmod +x ports/ci/flatpak/build.sh
          ./ports/ci/flatpak/build.sh
          echo
          echo Release Deploy
          echo
          chmod +x ports/ci/flatpak/deploy.sh
          ./ports/ci/flatpak/deploy.sh
          echo
          echo Compress files
          echo
          chmod +x ports/ci/flatpak/compress.sh
          ./ports/ci/flatpak/compress.sh
    - name: Daily build
      uses: uraimo/run-on-arch-action@v2
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      with:
        arch: ${{ matrix.architecture }}
        distro: ${{ matrix.distro }}
        githubToken: ${{ github.token }}
        dockerRunArgs: |
          -v "${{ github.workspace }}:/sources"
        env: |
          GITHUB_REF: "${{ env.GITHUB_REF }}"
          GITHUB_SERVER_URL: "${{ env.GITHUB_SERVER_URL }}"
          GITHUB_REPOSITORY: "${{ env.GITHUB_REPOSITORY }}"
          GITHUB_RUN_ID: "${{ env.GITHUB_RUN_ID }}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILE_PASSWORD: ${{ secrets.FILE_PASSWORD }}
          DISTRO: ${{ matrix.distro }}
          ARCHITECTURE: ${{ matrix.architecture }}
          NJOBS: ${{ env.NJOBS }}
          UPLOAD: ${{ matrix.upload }}
          DAILY_BUILD: 1
        run: |
          cd /sources
          echo
          echo Install dependencies
          echo
          chmod +x ports/ci/flatpak/install_deps.sh
          ./ports/ci/flatpak/install_deps.sh
          echo
          echo Daily Build
          echo
          chmod +x ports/ci/flatpak/build.sh
          ./ports/ci/flatpak/build.sh
          echo
          echo Daily Deploy
          echo
          chmod +x ports/ci/flatpak/deploy.sh
          ./ports/ci/flatpak/deploy.sh
          echo
          echo Compress files
          echo
          chmod +x ports/ci/flatpak/compress.sh
          ./ports/ci/flatpak/compress.sh
    - name: Release Upload
      uses: softprops/action-gh-release@v1
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      with:
        repository: webcamoid/WebcamoidPrivate
        files: webcamoid-packages/linux/*
      env:
        GITHUB_TOKEN: ${{ secrets.UPLOAD_TOKEN }}
    - name: Daily Build Upload
      uses: softprops/action-gh-release@v1
      if: ${{ !startsWith(github.ref, 'refs/tags/') && github.ref == 'refs/heads/master' }}
      with:
        repository: webcamoid/WebcamoidPrivate
        body: "${{ github.event.head_commit.message }} (commit: [${{ github.sha }}](https://github.com/webcamoid/webcamoid/commit/${{ github.sha }}))<hr>**Note**: Ignore the commit information of the tag, the files in the release keep updating with every new build, these packages were built from [${{ github.sha }}](https://github.com/webcamoid/webcamoid/commit/${{ github.sha }}) commit."
        prerelease: true
        files: webcamoid-packages/linux/*
        name: Daily Build
        tag_name: daily-build
      env:
        GITHUB_TOKEN: ${{ secrets.UPLOAD_TOKEN }}
#    - uses: actions/upload-artifact@v4
#      if: ${{ startsWith(github.ref, 'refs/tags/') && matrix.upload }}
#      with:
#        name: release-${{ matrix.architecture }}
#        overwrite: true
#        path: webcamoid-packages-*.7z
#    - uses: actions/upload-artifact@v4
#      if: ${{ !startsWith(github.ref, 'refs/tags/') && matrix.upload && github.ref == 'refs/heads/master' }}
#      with:
#        name: daily-build-${{ matrix.architecture }}
#        overwrite: true
#        path: webcamoid-packages-*.7z
