name: Fedora

on: [push, pull_request]

env:
  QTIFWVER: 4.1.1
  APPIMAGEVER: 12
  DOCKERIMG: fedora:rawhide
  FEDORAVER: rawhide
  NJOBS: 4

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 10
      fail-fast: false
      matrix:
       include:
         - compiler: gcc
         - compiler: clang
    env:
      COMPILER: ${{ matrix.compiler }}
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      uses: addnab/docker-run-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: gcr.io
        image: ${{ env.DOCKERIMG }}
        options: -v ${{ github.workspace }}:/sources
        run: |
          cd /sources
          chmod +x ports/ci/linux-fedora/install_deps.sh
          ./ports/ci/linux-fedora/install_deps.sh
    - name: Release Build
      uses: addnab/docker-run-action@v3
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      with:
        image: ${{ env.DOCKERIMG }}
        options: -v ${{ github.workspace }}:/sources
        run: |
          cd /sources
          chmod +x ports/ci/linux-fedora/build.sh
          ./ports/ci/linux-fedora/build.sh
    - name: Release Deploy
      uses: addnab/docker-run-action@v3
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      with:
        image: ${{ env.DOCKERIMG }}
        options: -v ${{ github.workspace }}:/sources
        run: |
          cd /sources
          chmod +x ports/ci/linux-fedora/deploy.sh
          ./ports/ci/linux-fedora/deploy.sh
    - name: Daily Build
      uses: addnab/docker-run-action@v3
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      env:
        DAILY_BUILD: 1
      with:
        image: ${{ env.DOCKERIMG }}
        options: -v ${{ github.workspace }}:/sources
        run: |
          cd /sources
          chmod +x ports/ci/linux-fedora/build.sh
          ./ports/ci/linux-fedora/build.sh
    - name: Daily Deploy
      uses: addnab/docker-run-action@v3
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      env:
        DAILY_BUILD: 1
      with:
        image: ${{ env.DOCKERIMG }}
        options: -v ${{ github.workspace }}:/sources
        run: |
          cd /sources
          chmod +x ports/ci/linux-fedora/deploy.sh
          ./ports/ci/linux-fedora/deploy.sh
