name: Arch Linux

on: [push, pull_request]

env:
  QTIFWVER: 4.1.1
  APPIMAGEVER: 12
  ARCH_ROOT_DATE: 2021.07.01
  ARCH_ROOT_URL: https://mirror.rackspace.com/archlinux
  NJOBS: 4

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 10
      fail-fast: false
      matrix:
       include:
         - compiler: gcc
         - compiler: clang
    env:
      COMPILER: ${{ matrix.compiler }}
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        chmod +x ports/ci/linux-arch/install_deps.sh
        ./ports/ci/linux-arch/install_deps.sh
    - name: Release Build
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      run: |
        chmod +x ports/ci/linux-arch/build.sh
        ./ports/ci/linux-arch/build.sh
    - name: Release Deploy
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      run: |
        chmod +x ports/ci/linux-arch/deploy.sh
        ./ports/ci/linux-arch/deploy.sh
    - name: Daily Build
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      env:
        DAILY_BUILD: 1
      run: |
        chmod +x ports/ci/linux-arch/build.sh
        ./ports/ci/linux-arch/build.sh
    - name: Daily Deploy
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      env:
        DAILY_BUILD: 1
      run: |
        chmod +x ports/ci/linux-arch/deploy.sh
        ./ports/ci/linux-arch/deploy.sh
