name: Snap

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        chmod +x ports/ci/snap/install_deps.sh
        ./ports/ci/snap/install_deps.sh
    - name: Release Build prepare
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      run: |
        chmod +x ports/ci/snap/build_prepare.sh
        ./ports/ci/snap/build_prepare.sh
    - name: Daily Build prepare
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      env:
        DAILY_BUILD: 1
      run: |
        chmod +x ports/ci/snap/build_prepare.sh
        ./ports/ci/snap/build_prepare.sh
    - name: Running snapcraft
      uses: snapcore/action-build@v1
      id: snapcraft
      with:
        snapcraft-args: --enable-experimental-extensions
    - name: Release Deploy
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      run: |
        chmod +x ports/ci/snap/deploy.sh
        ./ports/ci/snap/deploy.sh
    - name: Daily Deploy
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      env:
        DAILY_BUILD: 1
      run: |
        chmod +x ports/ci/snap/deploy.sh
        ./ports/ci/snap/deploy.sh
    - name: Release Upload
      uses: softprops/action-gh-release@v1
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      with:
        repository: webcamoid/WebcamoidPrivate
        files: webcamoid-packages/linux/*
      env:
        GITHUB_TOKEN: ${{ secrets.UPLOAD_TOKEN }}
    - name: Daily Build Upload
      uses: softprops/action-gh-release@v1
      if: ${{ !startsWith(github.ref, 'refs/tags/') && github.ref == 'refs/heads/master' }}
      with:
        repository: webcamoid/WebcamoidPrivate
        body: "${{ github.event.head_commit.message }} (commit: ${{ github.sha }})<hr>**Note**: Ignore the commit information of the tag, the files in the release keep updating with every new build, these packages were built from ${{ github.sha }} commit."
        prerelease: true
        files: webcamoid-packages/linux/*
        name: Daily Build
        tag_name: daily-build
      env:
        GITHUB_TOKEN: ${{ secrets.UPLOAD_TOKEN }}
